<?php

/**
 * Implements hook_preprocess_html().
 */
function mt_preprocess_html(&$variables) {
    // add to classes
    $variables['attributes']['class'][] = 'mt';
}

function mt_theme_suggestions_page_alter(array &$suggestions, array $variables) {
    // Add content type suggestions.
    if ($node = \Drupal::request()->attributes->get('node')) {
        array_splice($suggestions, 1, 0, 'page__node__' . $node->getType());
    }
}